[project]
name = "ai-slack-summary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "openai>=1.109.1",
    "python-dotenv>=1.1.1",
    "slack-sdk>=3.36.0",
]
